"""
Configuration exports.
"""

from .prompts import (
    FOUNDER_INITIAL_PROMPT,
    FOUNDER_ITERATION_PROMPT,
    INVESTOR_STEP1_PROPOSAL_EVALUATION_PROMPT,
    INVESTOR_STEP2_INITIAL_ALLOCATION_PROMPT,
    INVESTOR_STEP2_DEBATE_PROMPT,
)
from .config_10_founders_game import CONFIG_10_FOUNDERS
from .config_25_founders_6groups_investor_counts import CONFIG_25_FOUNDERS_6GROUPS_INVESTOR_COUNTS
from .config_25_founders_6groups_strategy import CONFIG_25_FOUNDERS_6GROUPS_STRATEGY
from .config_25_founders_multimodel import CONFIG_25_FOUNDERS_MULTIMODEL
from .config_multitask import CONFIG_25_FOUNDERS_5GROUPS_TASK_ALIGNED

__all__ = [
    "FOUNDER_INITIAL_PROMPT",
    "FOUNDER_ITERATION_PROMPT",
    "INVESTOR_STEP1_PROPOSAL_EVALUATION_PROMPT",
    "INVESTOR_STEP2_INITIAL_ALLOCATION_PROMPT",
    "INVESTOR_STEP2_DEBATE_PROMPT",
    "CONFIG_10_FOUNDERS",
    "CONFIG_25_FOUNDERS_6GROUPS_INVESTOR_COUNTS",
    "CONFIG_25_FOUNDERS_6GROUPS_STRATEGY",
    "CONFIG_25_FOUNDERS_MULTIMODEL",
    "CONFIG_25_FOUNDERS_5GROUPS_TASK_ALIGNED",
]
