"""
Configuration module.
"""

from .prompts import (
    FOUNDER_INITIAL_PROMPT,
    FOUNDER_ITERATION_PROMPT,
    INVESTOR_STEP1_PROPOSAL_EVALUATION_PROMPT,
)
from .default_config import DEFAULT_CONFIG

__all__ = [
    'DEFAULT_CONFIG',
    'FOUNDER_INITIAL_PROMPT',
    'FOUNDER_ITERATION_PROMPT',
    'INVESTOR_STEP1_PROPOSAL_EVALUATION_PROMPT',
]
