"""
Configuration module.
"""

from .prompts import (
    FOUNDER_INITIAL_PROMPT,
    FOUNDER_ITERATION_PROMPT,
    INVESTOR_EVALUATION_PROMPT,
    # INVESTOR_STRATEGY_UPDATE_PROMPT
)
from .default_config import DEFAULT_CONFIG

__all__ = [
    'DEFAULT_CONFIG',
    'FOUNDER_INITIAL_PROMPT',
    'FOUNDER_ITERATION_PROMPT',
    'INVESTOR_EVALUATION_PROMPT',
    # 'INVESTOR_STRATEGY_UPDATE_PROMPT',
]
